name: Latest blog post workflow
on:
  schedule:
    - cron: '48 7 * * mon,thu'
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Stackoverflow answers
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: 'https://stackoverflow.com/feeds/user/6216'
          date_format:	dddd, mmmm d, yyyy
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Updated readme with the latest blogposts"
          feed_list: 'https://alister.github.io/index.xml'
          date_format:	dddd, mmmm d, yyyy
          max_post_count: 3
